### ISSUE TITLE
SQL syntax error - column specified twice

### ISSUE THREAD

**Issue by kukoman** [tawfekov/ZF2EntityAudit#28]
Hi there,

I'm getting error SQLSTATE[42000] Column 'facility_id' specified twice. 
When I'm using an entity with simple column and same field is used for mapping as well, than it will translate to query with two identical fields. 
 
consider following entity example:
```php
class Facility
{
    /**
     * @ORM\Column(name="facility_id", type="integer")
     */
    private $facility_id;

    /**
     * @ORM\OneToOne(targetEntity="...")
     * @ORM\JoinColumn(name="facility_id", referencedColumnName="id")
     */
    private $facility;
}
```
Query:
```sql
INSERT INTO facility (rev, revtype, facility_id, facility_id)  VALUES (?, ?, ?, ?)
```

I'm using the column $facility_id for easy filtering with Doctrine\Common\Collections\Criteria and the $facility property for associations. 

Any advice appreciated.

**Comment by tawfekov** [comment]
sorry for being this late 
I don't think its related to my module , do you still have this issue ?
